### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by Vinidsg** [Vinidsg/trip-taker#4]
![triptaker-figma](https://user-images.githubusercontent.com/61765755/226067694-ec3bc43f-41ba-4dbc-94a2-c9c2faa4ae2f.png)

**Comment by MonjimaLahiri** [comment]
what is the issue here?

**Comment by Vinidsg** [comment]
Hi @MonjimaLahiri, there's no issue here, have you found any problem?

**Comment by MonjimaLahiri** [comment]
oh no, i was exploring for figma designs, and yours was listed in issues, so i was a bit confused if there is some issue or not.

**Comment by Vinidsg** [comment]
oh, sorry, I have added it wrongly, but thanks for the feedback ;)
